# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

volumes:
  opensearch-data1:
  opensearch-data2:

services:
  spark-master:
    container_name: spark_master
    image: docker.io/bitnami/spark:2
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - net
    volumes:
      - ./docker/spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties  
      - ./docker/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars:/opt/spark-jars 
    environment:
      - HADOOP_USER_NAME=root
      - SPARK_USER=root
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MODE=master
      - SPARK_CONF_DIR=/opt/spark-conf # Pointing to the directory with custom Spark configurations
      - SPARK_DRIVER_EXTRA_CLASSPATH=/opt/spark-jars/* # Add the jar to classpath for driver
      - SPARK_EXECUTOR_EXTRA_CLASSPATH=/opt/spark-jars/* # Add the jar to classpath for executor
      - SPARK_SQL_EXTENSIONS=org.opensearch.flint.FlintPPLSparkExtensions # Set the Spark SQL Extensions
  spark-worker-1:
    image: docker.io/bitnami/spark:2
    container_name: spark_worker1
    ports:
      - "9091:8080"
      - "7000:7000"
    networks:
      - net
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_MODE=worker
      - SPARK_LOCAL_IP=spark-worker-1
      - SPARK_DRIVER_EXTRA_CLASSPATH=/opt/spark-jars/*
      - SPARK_EXECUTOR_EXTRA_CLASSPATH=/opt/spark-jars/*
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./logs:/opt/spark-logs
  livy-server:
    container_name: livy_server
    build: ./docker/livy/
    command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
    user: root
    volumes:
      - type: bind
        source: ./docker/livy/conf/
        target: /opt/bitnami/livy/conf/
      - type: bind
        source: ./docker/livy/target/
        target: /target/
      - type: bind
        source: ./docker/livy/data/
        target: /data/
    ports:
      - '8998:8998'
    networks:
      - net
    depends_on:
      - spark-master
      - spark-worker-1
  opensearch-node1:
    image: opensearchproject/opensearch:${VERSION}
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - net
  opensearch-node2:
    image: opensearchproject/opensearch:${VERSION}
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${VERSION}
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # must be a string with no spaces when specified as an environment variable
    networks:
      - net

networks:
  net:
    driver: bridge